@startuml
package "Builder" {
  [ProgramaBuilder]
  [ReverserBuilder]
  [ContadorSubidaBuilder]
  [ContadorBajadaBuilder]
  [ProgramaDirector]
}

package "Productos" {
  [Reverser]
  [ContadorSubida]
  [ContadorBajada]
}

[ProgramaDirector] --> [ProgramaBuilder]

[ReverserBuilder] --> [Reverser]
[ContadorSubidaBuilder] --> [ContadorSubida]
[ContadorBajadaBuilder] --> [ContadorBajada]

@enduml
